"""Add order to Subseries

Revision ID: 1b8a7ec79dad
Revises: e82fc0244921
Create Date: 2022-08-08 23:13:10.204156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b8a7ec79dad"
down_revision = "e82fc0244921"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
