"""Initial revision

Revision ID: 4d98b82d53c0
Revises: 
Create Date: 2022-08-07 14:35:06.808120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d98b82d53c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Caption',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('episode_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('text', sa.String(length=256), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['Episode.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Caption_episode_id'), 'Caption', ['episode_id'], unique=False)
    op.create_table('Episode',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('subseries_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['subseries_id'], ['SubSeries.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Episode_name'), 'Episode', ['name'], unique=False)
    op.create_index(op.f('ix_Episode_subseries_id'), 'Episode', ['subseries_id'], unique=False)
    op.create_table('Series',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Series_name'), 'Series', ['name'], unique=False)
    op.create_table('SubSeries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('series_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['Series.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_SubSeries_name'), 'SubSeries', ['name'], unique=False)
    op.create_index(op.f('ix_SubSeries_series_id'), 'SubSeries', ['series_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SubSeries_series_id'), table_name='SubSeries')
    op.drop_index(op.f('ix_SubSeries_name'), table_name='SubSeries')
    op.drop_table('SubSeries')
    op.drop_index(op.f('ix_Series_name'), table_name='Series')
    op.drop_table('Series')
    op.drop_index(op.f('ix_Episode_subseries_id'), table_name='Episode')
    op.drop_index(op.f('ix_Episode_name'), table_name='Episode')
    op.drop_table('Episode')
    op.drop_index(op.f('ix_Caption_episode_id'), table_name='Caption')
    op.drop_table('Caption')
    # ### end Alembic commands ###
