"""Change relations

Revision ID: 5b5e1881c0ae
Revises: 1b8a7ec79dad
Create Date: 2022-08-08 23:25:44.055254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b5e1881c0ae"
down_revision = "1b8a7ec79dad"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
