"""Add posters

Revision ID: 981c389b1236
Revises: 81d1de28179f
Create Date: 2022-10-29 20:36:49.891542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "981c389b1236"
down_revision = "81d1de28179f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "Series", sa.Column("poster_path", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Series", "poster_path")
    # ### end Alembic commands ###
