"""Add order to Subseries

Revision ID: e82fc0244921
Revises: 4d98b82d53c0
Create Date: 2022-08-08 23:12:44.115065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e82fc0244921"
down_revision = "4d98b82d53c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "Caption", "Episode", ["episode_id"], ["id"], use_alter=True
    )
    op.add_column("Episode", sa.Column("order", sa.Integer(), nullable=True))
    op.add_column(
        "Episode", sa.Column("path", sa.String(length=256), nullable=False)
    )
    op.create_foreign_key(
        None, "Episode", "SubSeries", ["subseries_id"], ["id"], use_alter=True
    )
    op.add_column("SubSeries", sa.Column("order", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "SubSeries", "Series", ["series_id"], ["id"], use_alter=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "SubSeries", type_="foreignkey")
    op.drop_column("SubSeries", "order")
    op.drop_constraint(None, "Episode", type_="foreignkey")
    op.drop_column("Episode", "path")
    op.drop_column("Episode", "order")
    op.drop_constraint(None, "Caption", type_="foreignkey")
    # ### end Alembic commands ###
