"""Make relations cascade

Revision ID: eeba81b893e3
Revises: 0ed644dace18
Create Date: 2022-08-09 00:08:57.868078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eeba81b893e3"
down_revision = "0ed644dace18"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("Caption_episode_id_fkey", "Caption", type_="foreignkey")
    op.create_foreign_key(
        None,
        "Caption",
        "Episode",
        ["episode_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.drop_constraint(
        "Episode_subseries_id_fkey", "Episode", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "Episode",
        "SubSeries",
        ["subseries_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.drop_constraint(
        "SubSeries_series_id_fkey", "SubSeries", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "SubSeries",
        "Series",
        ["series_id"],
        ["id"],
        ondelete="CASCADE",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "SubSeries", type_="foreignkey")
    op.create_foreign_key(
        "SubSeries_series_id_fkey", "SubSeries", "Series", ["series_id"], ["id"]
    )
    op.drop_constraint(None, "Episode", type_="foreignkey")
    op.create_foreign_key(
        "Episode_subseries_id_fkey",
        "Episode",
        "SubSeries",
        ["subseries_id"],
        ["id"],
    )
    op.drop_constraint(None, "Caption", type_="foreignkey")
    op.create_foreign_key(
        "Caption_episode_id_fkey", "Caption", "Episode", ["episode_id"], ["id"]
    )
    # ### end Alembic commands ###
